prog:main.o timer.o #test.o
	gcc main.o timer.o # test.o -o prog -lSDL -lSDL_ttf -g -lSDL_image -lSDL_mixer
main1.o:main.c
	gcc -c main.c -g
timer.o:timer.c
	gcc -c timer.c -g
#test.o:test.c\
	gcc -c test.c -g